version: "3.9"

services:
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - db
    entrypoint: "go run ./cmd/zeronews"

  db:
    image: postgres:alpine
    #    image: schema
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
