version: "3.9"

services:
  web:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    entrypoint: "go run ./cmd/zeronews/main.go"

  db:
    image: postgres:alpine
    #    image: schema
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/zero_news_db?sslmode=disable
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 4s
      timeout: 2s
      retries: 10
